name: Apptainer Build Push

on:
  push:
    tags:
      - '*'           # Push events to every tag not containing /

jobs:
  build-test-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    container:
        image: kaczmarj/apptainer:latest
        options: --privileged

    name: Build Container
    steps:

      - name: Check Out Code
        uses: actions/checkout@v4

      - name: Build Download Containers
        run: |
          cd usecase-2.1 && apptainer build download.sif download.def && cd ..
          cd usecase-2.2 && apptainer build download.sif download.def && cd ..
          cd usecase-2.3 && apptainer build download.sif download.def && cd ..
          cd usecase-2.4 && apptainer build download.sif download.def && cd ..
          cd usecase-2.5 && apptainer build download.sif download.def && cd ..

      - name: Build Pipeline Containers
        run: |
          cd usecase-2.1 && apptainer build pipeline.sif container-r.def && cd ..  # there are also containers based on MATLAB, Python, and Julia
          cd usecase-2.2 && apptainer build pipeline.sif container.def && cd ..
          cd usecase-2.3 && apptainer build pipeline.sif container.def && cd ..
          cd usecase-2.4 && apptainer build pipeline.sif container.def && cd ..
          cd usecase-2.5 && apptainer build pipeline.sif container.def && cd ..

      - name: Build Infrastructure Containers
        run: |
          cd infrastructure
          apptainer build scramble.sif         infrastructure/scramble.def
          apptainer build singlesubject.sif    infrastructure/singlesubject.def
          apptainer build mergederivatives.sif infrastructure/mergederivatives.def
          apptainer build mergesubjects.sif    infrastructure/mergesubjects.def
          apptainer build leaveoneout.sif      infrastructure/leaveoneout.def
          # apptainer build mergegroup.sif       infrastructure/mergegroup.def
          # apptainer build calibratenoise.sif   infrastructure/calibratenoise.def
          # apptainer build addnoise.sif         infrastructure/addnoise.def
          cd ..

      - name: Login and Push Container
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | apptainer registry login -u "${{ github.actor }}" --password-stdin oras://ghcr.io
          apptainer push usecase-2.1/download.sif oras://ghcr.io/${{ github.repository_owner }}/download-2.1.sif:${GITHUB_REF_NAME}
          apptainer push usecase-2.2/download.sif oras://ghcr.io/${{ github.repository_owner }}/download-2.2.sif:${GITHUB_REF_NAME}
          apptainer push usecase-2.3/download.sif oras://ghcr.io/${{ github.repository_owner }}/download-2.3.sif:${GITHUB_REF_NAME}
          apptainer push usecase-2.4/download.sif oras://ghcr.io/${{ github.repository_owner }}/download-2.4.sif:${GITHUB_REF_NAME}
          apptainer push usecase-2.5/download.sif oras://ghcr.io/${{ github.repository_owner }}/download-2.5.sif:${GITHUB_REF_NAME}

          apptainer push usecase-2.1/pipeline.sif oras://ghcr.io/${{ github.repository_owner }}/pipeline-2.1.sif:${GITHUB_REF_NAME}
          apptainer push usecase-2.2/pipeline.sif oras://ghcr.io/${{ github.repository_owner }}/pipeline-2.2.sif:${GITHUB_REF_NAME}
          apptainer push usecase-2.3/pipeline.sif oras://ghcr.io/${{ github.repository_owner }}/pipeline-2.3.sif:${GITHUB_REF_NAME}
          apptainer push usecase-2.4/pipeline.sif oras://ghcr.io/${{ github.repository_owner }}/pipeline-2.4.sif:${GITHUB_REF_NAME}
          apptainer push usecase-2.5/pipeline.sif oras://ghcr.io/${{ github.repository_owner }}/pipeline-2.5.sif:${GITHUB_REF_NAME}

          apptainer push infrastructure/scramble.sif         oras://ghcr.io/${{ github.repository_owner }}/scramble.sif:${GITHUB_REF_NAME}
          apptainer push infrastructure/singlesubject.sif    oras://ghcr.io/${{ github.repository_owner }}/singlesubject.sif:${GITHUB_REF_NAME}
          apptainer push infrastructure/mergederivatives.sif oras://ghcr.io/${{ github.repository_owner }}/mergederivatives.sif:${GITHUB_REF_NAME}
          apptainer push infrastructure/mergesubjects.sif    oras://ghcr.io/${{ github.repository_owner }}/mergesubjects.sif:${GITHUB_REF_NAME}
          apptainer push infrastructure/leaveoneout.sif      oras://ghcr.io/${{ github.repository_owner }}/leaveoneout.sif:${GITHUB_REF_NAME}
          # apptainer push infrastructure/mergegroup.sif       oras://ghcr.io/${{ github.repository_owner }}/mergegroup.sif:${GITHUB_REF_NAME}
          # apptainer push infrastructure/calibratenoise.sif   oras://ghcr.io/${{ github.repository_owner }}/calibratenoise.sif:${GITHUB_REF_NAME}
          # apptainer push infrastructure/addnoise.sif         oras://ghcr.io/${{ github.repository_owner }}/addnoise.sif:${GITHUB_REF_NAME}