name: BIDScramble tests
on:
  push:
    paths:
      - 'BIDScramble/**'
      - '!**.md'
      - '!**.rst'
  pull_request:
    paths:
      - 'BIDScramble/**'
      - '!**.md'
      - '!**.rst'

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./BIDScramble

    steps:
      - uses: actions/checkout@v3
      - name: Tests with pytest
        run: |
          pip install --upgrade pip
          pip install .[fif] pytest
          pytest tests
