name: mergesubjects tests
on:
  workflow_dispatch:
  push:
    paths:
      - 'infrastructure/mergesubjects/**'
      - '!**.md'
  pull_request:
    paths:
      - 'infrastructure/mergesubjects/**'
      - '!**.md'

jobs:
  tests:
    name: Run pytests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infrastructure/mergesubjects

    steps:
      - uses: actions/checkout@v3
      - name: Tests with pytest
        run: |
          pip install --upgrade pip
          pip install pytest
          pytest .