name: mergegroup tests
on:
  workflow_dispatch:
  push:
    paths:
      - 'infrastructure/mergegroup/**'
      - '!**.md'
  pull_request:
    paths:
      - 'infrastructure/mergegroup/**'
      - '!**.md'

jobs:
  tests:
    name: Run pytests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infrastructure/mergegroup

    steps:
      - uses: actions/checkout@v3
      - name: Tests with pytest
        run: |
          pip install --upgrade pip
          pip install pytest pandas h5py scipy nibabel numpy more_itertools
          pytest .